### ISSUE TITLE
access denied errors when users are not logged in should redirect to the log in page.

### ISSUE THREAD

**Issue by rl-utility-man** [signebedi/libreforms-fastapi#229]
right now, when an un authenticated user attempts to access restricted content, they get an inscrutable error message. It would be better to redirect them to the log in page and possibly display a helpful message.

**Comment by signebedi** [comment]
All authenticated users have the user scope "authenticated", and admins have the additional scope of "admin". I implemented this such that regular UI pages redirect a user to the login page when a user is unauthenticated. When a page requires the admin scope, we redirect to the homepage, since in some cases the user may actually be authenticated, so there is no point sending them to the login page.

I use the starlette authentication system that ships with fastapi. Specifically, the @requires decorator, see https://github.com/encode/starlette/blob/d1b38037e71a1790a1a8bc55c6e7dfb95d69c5bc/starlette/authentication.py#L30
