### ISSUE TITLE
add an option to put the JSON of submitted forms into an email to a designated person

### ISSUE THREAD

**Issue by rl-utility-man** [signebedi/libreforms-fastapi#244]
this is probably an interim solution and can be hard coded

**Comment by signebedi** [comment]
We are planning to add form event hooks in #210. This will allow us to describe custom logic that runs on certain triggers, like form creation, edit, deletion, approval - to name just a few. I think that this feature is probably best to implement through those event hooks once that feature is added. That way, it can fall under the scope of the end user to write and maintain custom logic for how they want to route form data; additionally, it minimizes use-case-specific bloat in an otherwise generalizable code base.
