### ISSUE TITLE
distinguish form templates and form submissions concept which are currently both called "form"

### ISSUE THREAD

**Issue by rl-utility-man** [signebedi/libreforms-fastapi#285]
for example, switch from all_forms_ to all_submissions

**Comment by signebedi** [comment]
Great idea! Added!

Please help me keep a look out for places where we confuse this terminology. This is not the only location. For example, we refer to submissions as "documents" in the admin interface, see:

![image](https://github.com/signebedi/libreforms-fastapi/assets/54920695/c4805af5-f22d-4124-b18b-43ec49d74c4e)

I'll make modifications so that this interface is also using the common terminology of "submissions", and tag my commits with this issue number so we can use this issue to organize a broader cleanup effort to standardize terminology along the industry-standard.
